FROM ruby:2.5.1

MAINTAINER Hesham Salah "hs414h@gmail.com"

RUN apt-get update -qq && apt-get install -y build-essential \
                                             postgresql-client \
                                             nodejs \
                                             libxml2-dev \
                                             libxslt1-dev \
                                             imagemagick \
                                             nano \
                                             less \
                                             cron \
                                             curl

ENV app /var/app
ENV RAILS_ENV production
ENV RACK_ENV production

RUN mkdir -p $app
WORKDIR $app

# --- install bundler ---
RUN gem install bundler

COPY ./Gemfile .

COPY ./Gemfile.lock .

RUN bundle install

COPY . .

EXPOSE 3000

RUN chmod +x ./.docker/entry_point.sh

ENTRYPOINT ["./.docker/entry_point.sh"]